# Azure Databricks Build Pipeline
# azure-pipelines.yml

trigger:
- main

pool:
  name: windows-2019

steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: dbnotebooks'
  inputs:
    PathtoPublish: notebooks/samplenotebook.py
    ArtifactName: dbnotebooks
