# Azure Databricks Build Pipeline
# azure-pipelines.yml

trigger:
- main

pool:
  name: Hosted Ubuntu 1604

steps:
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'